sonar.projectKey=sSailSs_TournaBadV2
sonar.organization=ssailss
sonar.projectName=TournaBadV2
sonar.sourceEncoding=UTF-8

sonar.sources=app,config,database,public,resources,routes
sonar.tests=tests

sonar.exclusions=vendor/**,node_modules/**,storage/**,bootstrap/cache/**,public/build/**
sonar.test.exclusions=tests/**
